services:
  mjw_app:
    image: mjw_app:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mjw_app_container
    environment:
      - NEXT_PUBLIC_MJW_BASE_URL=http://localhost:8080
    ports:
      - '3000:3000'
