services:
  mjw_app:
    image: mjw_app:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_MJW_BASE_URL=http://mjwappvm.dev:3000
        - HELLO=helloFromComposeArgs
    container_name: mjw_app_container
    environment:
      - NODE_ENV=production
      - HELLO=helloFromCompose
      - NEXT_PUBLIC_MJW_BASE_URL=http://mjwappvm.dev:3000
    ports:
      - '3000:3000'
