services:
  mjw_app:
    image: mjw_app:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_FILE: ${ENV_FILE:-.env}
    container_name: mjw_app_container
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_HELLO=helloOverriden
    env_file:
      # Specify the environment files as a list of strings
      - path: .env
        required: true # Default environment file
      - path: .env.docker.mjwapp
        required: false
    ports:
      - '3000:3000'
