services:
  mjw_app:
    image: mjw_app:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mjw_app_container
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_HELLO=helloFromCompose
      - NEXT_PUBLIC_MJW_BASE_URL=urlFromCompose
    ports:
      - '3000:3000'
